apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sqlsvr
  name: sqlsvr
spec:
  containers:
  - image: nginx
    name: sqlsvr
    envFrom:
    - secretRef:
        name: DB_PASSWORD
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
